### PR TITLE
fix issue #93

### PR DESCRIPTION
**Pull request by aniketkuma-r**
footer social icons overlapping fix. #93

### CODE REVIEW

**Review by pooranjoyb — CHANGES_REQUESTED** [review]
I cannot see any specific changes regarding `bug-fix` or some `Change in CSS`.
Please mention the changes you made. @aniketkuma-r

**Comment by aniketkuma-r** [comment]
the issue has already been fixed in #88  by someone else. but some how changes are not reflected on the hosted website. the CSS was already working fine in local setup at my `localhost:5173/contact` there is nothing to change in CSS. code is fine I have checked all the code properly.
I guess there is problem with gh-pages or something with hosting platform that why changes are not reflected even after PR got merged.

**Comment by aniketkuma-r** [comment]
I agree there is no significant change in my code but still I tried to refactor the code quality to some extinct. as the issue was already resolved but not reflected in website. i can't do any change from my end in the code to fix in hosted website as CSS is already fine. and working fine in local setup.

**Comment by pooranjoyb** [comment]
Got it @aniketkuma-r 👍 
Thanks for clarification. Actually I haven't updated the build in the `gh-pages` as some bugs were found. 
So, as this the `issue` is fixed. I'll close it then. Hope you find some more issues to work on :)

**Pull request closed without merging**
