### PR TITLE
Nav bar

### PR DESCRIPTION
**Pull request by GauravP23**
Nav-bar padding and enhancement.

image_2023-10-17_212341331

### CODE REVIEW

**Comment by GauravP23** [comment]
Kindly merge it with **_hacktoberfest-accepted_** label.

**Comment by pooranjoyb** [comment]
Could you also colorize the Hover Animations with the respective Navbar colors?

image

**Comment by GauravP23** [comment]
Sure .

**Comment by pooranjoyb** [comment]
Nice work @GauravP23 🎊

**Pull request merged**
