### PR TITLE
"Added shadow using framer-motion"

### PR DESCRIPTION
**Pull request by falgun143**
Please review my pr.

### CODE REVIEW

**Comment by pooranjoyb** [comment]
Hey @falgun143 , Nice work with the issue, but the animation is not looking that good as of now, esp the yellow tint. 
Please donot add that shadow. The hover animation is good tho.

**Comment by falgun143** [comment]
@pooranjoyb  ok going to change that now.And update it .

**Comment by falgun143** [comment]
@pooranjoyb please check.

**Comment by pooranjoyb** [comment]
Please resolve the conflicts. @falgun143

**Pull request closed without merging**
